# This file lists tools managed by Rokit, a toolchain manager for Roblox projects.
# For more information, see https://github.com/rojo-rbx/rokit

# New tools can be added by running `rokit add <tool>` in a terminal.

[tools]
darklua = "seaofvoices/darklua@0.16.0"
wally-package-types = "johnnymorganz/wally-package-types@1.5.1"
wally = "UpliftGames/wally@0.3.2"
rojo = "rojo-rbx/rojo@7.5.1"
stylua = "johnnymorganz/stylua@2.1.0"
selene = "kampfkarren/selene@0.28.0"
run-in-roblox = "rojo-rbx/run-in-roblox@0.3.0"
luau-lsp = "johnnymorganz/luau-lsp@1.52.0"
